name: build
env:
  DOTNET_NOLOGO: true

on: 
  push:
    branches: [main, dev]  
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build-${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ windows-latest ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      # Install GH CLI
      - run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh
        if: matrix.os == 'ubuntu-latest'
      - run: |
          Set-ExecutionPolicy RemoteSigned -scope CurrentUser
          iwr -useb get.scoop.sh | iex
          scoop install gh
        if: matrix.os == 'windows-latest'

      - run: gh --version

      # Install GCM Core
      - run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh
        if: matrix.os == 'ubuntu-latest'
      - run: |
          brew tap microsoft/git
          brew cask install git-credential-manager-core
        if: matrix.os == 'macOS-latest'
      - run: scoop install gh
        if: matrix.os == 'windows-latest'

      - run: dotnet tool install -g --version 0.2.0-alpha dotnet-gcm
      - run: dotnet gcm store --protocol=https --host=github.com --username=daniel@cazzulino.com --password=${{ secrets.GITHUB_TOKEN }}
        # ubuntu-latest pending GCM Core installation support
        if: matrix.os != 'ubuntu-latest'
      - run: dotnet tool install -g dotnet-file
      - run: dotnet file add https://github.com/kzu/secrets/blob/main/.netconfig.user
        # ubuntu-latest pending GCM Core installation support
        if: matrix.os != 'ubuntu-latest'
      - run: dotnet tool install -g dotnet-config
      - run: dotnet config sleet.version
